language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os:
  - linux

before install:
  - sudo chmod 755 Scripts/install.sh Scripts/run_tests.sh

install:
  - sudo ./Scripts/install.sh

script:
  - mkdir build && cd build && cmake .. && make

after_script:
  - cd .. && ./Scripts/run_tests.sh
