language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os:
  - linux

before install:
  - sudo chmod 755 Scripts/install.sh
  - sudo chmod 755 Scripts/build_and_run.sh

install:
  - sudo ./Scripts/install.sh

script:
  - cd Scripts/
  - ./build_and_run.sh
  - ./build_and_run.sh -t
