language: cpp
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os:
  - linux

before install:
  - sudo apt update -qq

install:
  - sudo apt install -y libcurl4-openssl-dev libglew-dev libglfw3-dev libglfw3

script:
  - cmake .
  - make

